export const GET_DATA = 'GET_DATA';
export const CREATE_CHECKLIST = 'CREATE_CHECKLIST';
export const CREATE_TASK = 'CREATE_TASK';
export const CHECKLIST_DETAILS = 'CHECKLIST_DETAILS'
export const EDIT_COMPLETED = 'EDIT_COMPLETED'; 
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST'; 
export const DELETE_TASK = 'DELETE_TASK'; 